version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
    reviewers: ["fryorcraken"]
    # Update the npm manifest file to relax
    # the version requirements as js-waku is a library
    versioning-strategy: widen
    # Do not auto rebase, let bors handle this
    # rebase-strategy: "disabled"
  - package-ecosystem: "npm"
    directory: "/packages/byte-utils"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
    reviewers: ["fryorcraken"]
    # Update the npm manifest file to relax
    # the version requirements as js-waku is a library
    versioning-strategy: widen
    # Do not auto rebase, let bors handle this
    # rebase-strategy: "disabled"
  - package-ecosystem: "npm"
    directory: "/packages/core"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
    reviewers: ["fryorcraken"]
    # Update the npm manifest file to relax
    # the version requirements as js-waku is a library
    versioning-strategy: widen
    # Do not auto rebase, let bors handle this
    # rebase-strategy: "disabled"
  - package-ecosystem: "npm"
    directory: "/packages/create"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
    reviewers: ["fryorcraken"]
    # Update the npm manifest file to relax
    # the version requirements as js-waku is a library
    versioning-strategy: widen
    # Do not auto rebase, let bors handle this
    # rebase-strategy: "disabled"
  - package-ecosystem: "npm"
    directory: "/packages/dns-discovery"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
    reviewers: ["fryorcraken"]
    # Update the npm manifest file to relax
    # the version requirements as js-waku is a library
    versioning-strategy: widen
    # Do not auto rebase, let bors handle this
    # rebase-strategy: "disabled"
  - package-ecosystem: "npm"
    directory: "/packages/enr"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
    reviewers: ["fryorcraken"]
    # Update the npm manifest file to relax
    # the version requirements as js-waku is a library
    versioning-strategy: widen
    # Do not auto rebase, let bors handle this
    # rebase-strategy: "disabled"
  - package-ecosystem: "npm"
    directory: "/packages/interfaces"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
    reviewers: ["fryorcraken"]
    # Update the npm manifest file to relax
    # the version requirements as js-waku is a library
    versioning-strategy: widen
    # Do not auto rebase, let bors handle this
    # rebase-strategy: "disabled"
  - package-ecosystem: "npm"
    directory: "/packages/libp2p-utils"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
    reviewers: ["fryorcraken"]
    # Update the npm manifest file to relax
    # the version requirements as js-waku is a library
    versioning-strategy: widen
    # Do not auto rebase, let bors handle this
    # rebase-strategy: "disabled"
  - package-ecosystem: "npm"
    directory: "/packages/message-encryption"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
    reviewers: ["fryorcraken"]
    # Update the npm manifest file to relax
    # the version requirements as js-waku is a library
    versioning-strategy: widen
    # Do not auto rebase, let bors handle this
    # rebase-strategy: "disabled"
  - package-ecosystem: "npm"
    directory: "/packages/peer-exchange"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
    reviewers: ["fryorcraken"]
    # Update the npm manifest file to relax
    # the version requirements as js-waku is a library
    versioning-strategy: widen
    # Do not auto rebase, let bors handle this
    # rebase-strategy: "disabled"
  - package-ecosystem: "npm"
    directory: "/packages/proto"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
    reviewers: ["fryorcraken"]
    # Update the npm manifest file to relax
    # the version requirements as js-waku is a library
    versioning-strategy: widen
    # Do not auto rebase, let bors handle this
    # rebase-strategy: "disabled"
  - package-ecosystem: "npm"
    directory: "/packages/tests"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
    reviewers: ["fryorcraken"]
    # Update the npm manifest file to relax
    # the version requirements as js-waku is a library
    versioning-strategy: widen
    # Do not auto rebase, let bors handle this
    # rebase-strategy: "disabled"
