version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    reviewers:
      - "d4nte"
  - package-ecosystem: "npm"
    directory: "/examples/web-chat"
    schedule:
      interval: "weekly"
      day: "sunday"
    reviewers:
      - "d4nte"
