version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
    reviewers: ["fryorcraken"]
    # Update the npm manifest file to relax
    # the version requirements as js-waku is a library
    versioning-strategy: widen
    # Do not auto rebase, let bors handle this
    rebase-strategy: "disabled"
