version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 2
    schedule:
      interval: "daily"
    reviewers: ["fryorcraken","danisharora099","weboko"]
    versioning-strategy: increase
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
