queue_rules:
  - name: default
    conditions:
      - check-success="build_and_test (14, ubuntu-latest)"
      - check-success="build_and_test (14, macos-latest)"
      - check-success="examples_build_and_test (web-chat)"
      - check-success="examples_build_and_test (cli-chat)"

pull_request_rules:
  - name: automatic merge for main when ready and CI passes
    conditions:
      - check-success="build_and_test (14, ubuntu-latest)"
      - check-success="build_and_test (14, macos-latest)"
      - check-success="examples_build_and_test (web-chat)"
      - check-success="examples_build_and_test (cli-chat)"
      - author=D4nte
      - base=main
      - label=ready-to-merge
      - label!=work-in-progress
    actions:
      queue:
        name: default
