name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: install using npm ci
        uses: bahmutov/npm-install@v1

      - name: build
        run: npm build

      - name: test
        run: npm test
