name: CI

on:
  push:
    branches:
      - 'main'
      - 'staging'
      - 'trying'
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Get nim-waku HEAD
        id: nim-waku-head
        shell: bash
        run: cd nim-waku && echo "::set-output name=ref::$(git rev-parse HEAD)"

      - name: Cache nim-waku binary
        id: cache-nim-waku
        uses: actions/cache@v2
        with:
          path: |
            ./nim-waku/build/wakunode2
            ./nim-waku/vendor/rln/target/debug
          key: nim-waku-build-v2-${{ steps.nim-waku-head.outputs.ref }}

        # This would have been done part of npm pretest but it gives better
        # visibility in the CI if done as a separate step
      - name: Build wakunode2
        if: steps.cache-nim-waku.outputs.cache-hit != 'true'
        shell: bash
        run: cd nim-waku && make wakunode2

      - name: Install bufbuild
        uses: mu-io/setup-buf@v1beta
        with:
          buf-version: '0.39.1'

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache npm cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: node-v1-${{ hashFiles('**/package-lock.json') }}

      - name: install using npm ci
        uses: bahmutov/npm-install@v1

      - name: build
        run: npm run build

      - name: test
        run: npm run test
