name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Init submodules
        run: git submodule update --init --recursive

      - name: Cache nim-waku binary
        uses: actions/cache@v2
        with:
          path: ./nim-waku/build/wakunode2
          key: nim-waku-build-v1-${{ hashFiles('.gitmodules') }}

      - name: Install bufbuild
        uses: mu-io/setup-buf@v1beta
        with:
          buf-version: '0.39.1'

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: install using npm ci
        uses: bahmutov/npm-install@v1

      - name: build
        run: npm run build

      - name: test
        run: npm run test
